apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app.kubernetes.io/name: spring-petclinic
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: ghcr.io/nordhof/spring-petclinic-teamcity-demo:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
