apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  labels:
    app.kubernetes.io/name: spring-petclinic
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-public-network: "true"
    load-balancer.hetzner.cloud/name: "teamcity-certification-lb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-petclinic
